export const dummyTodoItems = [
    {
        id: 1,
        task: "Write project proposal for AI fitness app",
        category: "Work",
        dueDate: "2025-06-08",
        priority: "High",
        completed: false,
    },
    {
        id: 2,
        task: "Buy groceries: milk, eggs, vegetables",
        category: "Personal",
        dueDate: "2025-06-06",
        priority: "Medium",
        completed: false,
    },
    {
        id: 3,
        task: "Call dentist for appointment reschedule",
        category: "Health",
        dueDate: "2025-06-07",
        priority: "Low",
        completed: true,
    },
    {
        id: 4,
        task: "Study PostgreSQL indexing and query optimization",
        category: "Learning",
        dueDate: "2025-06-09",
        priority: "High",
        completed: false,
    },
    {
        id: 5,
        task: "Clean up downloads folder",
        category: "Personal",
        dueDate: "2025-06-10",
        priority: "Low",
        completed: false,
    },
    {
        id: 6,
        task: "Push updates to GitHub portfolio",
        category: "Work",
        dueDate: "2025-06-06",
        priority: "Medium",
        completed: true,
    },
];
